rewrite using tools-cache (#25)
* rewrite using tools-cache

bump dependencies, more tests

diff --git a/.github/workflows/check_url.yml b/.github/workflows/check_url.yml
--- a/.github/workflows/check_url.yml
+++ b/.github/workflows/check_url.yml
@@ -1,4 +1,3 @@
-# name: Simple url check
 on: [push]
 
 jobs:
@@ -7,11 +6,48 @@ jobs:
     timeout-minutes: 10
     strategy:
       matrix:
-        os: [ubuntu-latest, ubuntu-20.04]
+        os: [ubuntu-latest, windows-latest]
+    steps:
+
+      - name: Setup Babashka
+        id: setup-babashka-1
+        uses: turtlequeue/setup-babashka@main
+        with:
+          babashka-version: 1.3.189
+
+      - name: Check if bb runs fine
+        run: bb --version
+
+      - name: Setup Babashka from cache
+        id: setup-babashka-2
+        uses: turtlequeue/setup-babashka@main
+        with:
+          babashka-version: 1.3.189
+          fail-on-cache-miss: true
+
+      - name: Check if bb runs fine from cache
+        run: bb --version
+
+      - name: Test Cache
+        run: |
+          if [ -z "${{ steps.setup-babashka-1.outputs.cache-hit }}" ]; then
+            echo "Cache-hit output not set in first run. Failing the job."
+            exit 1
+          elif [ "${{ steps.setup-babashka-2.outputs.cache-hit }}" != "true" ]; then
+            echo "Cache not used in the second run. Failing the job."
+            exit 1
+          fi
+        shell: bash
+
+  check-url:
+    runs-on: ubuntu-latest
+    timeout-minutes: 10
+    strategy:
+      matrix:
         babashka-url: ['https://github.com/babashka/babashka/releases/download/v1.3.189/babashka-1.3.189-linux-amd64-static.tar.gz']
     steps:
       - name: Setup Babashka
-        id: setup-babashka
+        id: setup-babashka-1
         uses: turtlequeue/setup-babashka@main
         with:
           babashka-version: 1.3.189
@@ -26,9 +62,22 @@ jobs:
         with:
           babashka-version: 1.3.189
           babashka-url: ${{ matrix.babashka-url }}
+          fail-on-cache-miss: true
 
       - name: Check if bb runs fine from cache
         run: bb --version
+
+      - name: Test Cache
+        run: |
+          if [ -z "${{ steps.setup-babashka-1.outputs.cache-hit }}" ]; then
+            echo "Cache-hit output not set in first run. Failing the job."
+            exit 1
+          elif [ "${{ steps.setup-babashka-2.outputs.cache-hit }}" != "true" ]; then
+            echo "Cache not used in the second run. Failing the job."
+            exit 1
+          fi
+        shell: bash
+
   check-windows:
     # https://ci.appveyor.com/project/borkdude/babashka
     runs-on: windows-latest
@@ -37,8 +86,9 @@ jobs:
         babashka-url: ['https://ci.appveyor.com/api/buildjobs/hgg0343wy6uj4xog/artifacts/babashka-1.3.190-SNAPSHOT-windows-amd64.zip']
     steps:
       - name: Setup Babashka
-        id: setup-babashka
+        id: setup-babashka-1
         uses: turtlequeue/setup-babashka@main
+
         with:
           babashka-version: 1.3.190-SNAPSHOT
           babashka-url: ${{ matrix.babashka-url }}
@@ -49,9 +99,22 @@ jobs:
       - name: Setup Babashka from cache
         id: setup-babashka-2
         uses: turtlequeue/setup-babashka@main
+
         with:
           babashka-version: 1.3.190-SNAPSHOT
           babashka-url: ${{ matrix.babashka-url }}
+          fail-on-cache-miss: true
 
       - name: Check if bb runs fine from cache
         run: bb --version
+
+      - name: Test Cache
+        run: |
+          if [ -z "${{ steps.setup-babashka-1.outputs.cache-hit }}" ]; then
+            echo "Cache-hit output not set in first run. Failing the job."
+            exit 1
+          elif [ "${{ steps.setup-babashka-2.outputs.cache-hit }}" != "true" ]; then
+            echo "Cache not used in the second run. Failing the job."
+            exit 1
+          fi
+        shell: bash
