rewrite using tools-cache
bump dependencies, more tests

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -3,14 +3,23 @@ name: Main dev test
 on: [push]
 
 jobs:
-  simple:
-    runs-on: ubuntu-latest
-    # runs-on: windows-latest
+  maindevtest:
+    # runs-on: ubuntu-latest
+    runs-on: windows-latest
     steps:
       - name: Setup Babashka
-        uses: turtlequeue/setup-babashka@main
+        id: setup-babashka
+        uses: turtlequeue/setup-babashka@feat/cache
         with:
           babashka-version: 1.3.189
 
       - name: Check bb runs
         run: bb --version
+
+      - name: Test Cache
+        run: |
+          if [ -z "${{ steps.setup-babashka.outputs.cache-hit }}" ]; then
+            echo "Cache-hit output not set in first run. Failing the job."
+            exit 1
+           fi
+        shell: bash
diff --git a/.github/workflows/self_check.yml b/.github/workflows/self_check.yml
--- a/.github/workflows/self_check.yml
+++ b/.github/workflows/self_check.yml
@@ -7,12 +7,12 @@ jobs:
     runs-on: ${{ matrix.os }}
     strategy:
       matrix:
-        os: [ubuntu-latest, ubuntu-20.04, macos-latest, windows-latest]
-        babashka-version: [0.5.0, 1.1.172, 1.3.189]
+        os: [ubuntu-latest, macos-latest, windows-latest]
+        babashka-version: [1.1.172, 1.3.189]
     steps:
       - name: Setup Babashka
-        id: setup-babashka
-        uses: turtlequeue/setup-babashka@main
+        id: setup-babashka-1
+        uses: turtlequeue/setup-babashka@feat/cache
         with:
           babashka-version: ${{ matrix.babashka-version }}
 
@@ -21,9 +21,21 @@ jobs:
 
       - name: Setup Babashka from cache
         id: setup-babashka-2
-        uses: turtlequeue/setup-babashka@main
+        uses: turtlequeue/setup-babashka@feat/cache
         with:
           babashka-version: ${{ matrix.babashka-version }}
+          fail-on-cache-miss: true
 
       - name: Check if bb runs fine from cache
         run: bb --version
+
+      - name: Test Cache
+        run: |
+          if [ -z "${{ steps.setup-babashka-1.outputs.cache-hit }}" ]; then
+            echo "Cache-hit output not set in first run. Failing the job."
+            exit 1
+          elif [ "${{ steps.setup-babashka-2.outputs.cache-hit }}" != "true" ]; then
+            echo "Cache not used in the second run. Failing the job."
+            exit 1
+          fi
+        shell: bash
