test cache

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -14,3 +14,14 @@ jobs:
 
       - name: Check bb runs
         run: bb --version
+
+      - name: Test Cache
+        run: |
+          if [ -z "${{ steps.setup-babashka-1.outputs.cache-hit }}" ]; then
+            echo "Cache-hit output not set in first run. Failing the job."
+            exit 1
+          elif [ "${{ steps.setup-babashka-2.outputs.cache-hit }}" != "true" ]; then
+            echo "Cache not used in the second run. Failing the job."
+            exit 1
+          fi
+        shell: bash
diff --git a/.github/workflows/self_check.yml b/.github/workflows/self_check.yml
--- a/.github/workflows/self_check.yml
+++ b/.github/workflows/self_check.yml
@@ -25,13 +25,16 @@ jobs:
         with:
           babashka-version: ${{ matrix.babashka-version }}
 
+      - name: Check if bb runs fine from cache
+        run: bb --version
+
       - name: Test Cache
         run: |
-          if [ "${{ steps.setup-babashka-1.outputs.cache-hit }}" != "true" ] && [ "${{ steps.setup-babashka-2.outputs.cache-hit }}" != "true" ]; then
-            echo "Cache not used. Failing the job."
+          if [ -z "${{ steps.setup-babashka-1.outputs.cache-hit }}" ]; then
+            echo "Cache-hit output not set in first run. Failing the job."
+            exit 1
+          elif [ "${{ steps.setup-babashka-2.outputs.cache-hit }}" != "true" ]; then
+            echo "Cache not used in the second run. Failing the job."
             exit 1
           fi
         shell: bash
-
-      - name: Check if bb runs fine from cache
-        run: bb --version
