bump dependencies, better caching tests

diff --git a/.github/workflows/self_check.yml b/.github/workflows/self_check.yml
--- a/.github/workflows/self_check.yml
+++ b/.github/workflows/self_check.yml
@@ -7,8 +7,8 @@ jobs:
     runs-on: ${{ matrix.os }}
     strategy:
       matrix:
-        os: [ubuntu-latest, ubuntu-18.04, macos-latest, windows-latest]
-        babashka-version: [0.5.0, 1.1.172]
+        os: [ubuntu-latest, macos-latest, windows-latest]
+        babashka-version: [0.5.0, 1.3.188]
     steps:
       - name: Setup Babashka
         id: setup-babashka
@@ -24,6 +24,14 @@ jobs:
         uses: turtlequeue/setup-babashka@main
         with:
           babashka-version: ${{ matrix.babashka-version }}
+
+      - name: Test Cache
+        run: |
+          if [ "${{ steps.setup-babashka-1.outputs.cache-hit }}" != "true" ] && [ "${{ steps.setup-babashka-2.outputs.cache-hit }}" != "true" ]; then
+            echo "Cache not used. Failing the job."
+            exit 1
+          fi
+        shell: bash
 
       - name: Check if bb runs fine from cache
         run: bb --version
